---
    observation:
        "/mux/intervention":
            type: Bool
            remap: "intervention"
            options:
                stamped: True

        "/warty/forward/image":
            type: Image
            remap: "image_rgb"
            options:
                output_resolution: [64, 64]
                nchannels: 3

    action:
        "/warty/joy_teleop/cmd_vel_stamped":
            type: Twist
            options:
                mode: action
                stamped: true

    dt: 0.1
