---
    observation:
        "/odometry/filtered_odom":
            type: Odometry
            remap: "state"

        "/mux/intervention":
            type: Bool
            remap: "intervention"
            options:
                stamped: True

        "/multisense/left/image_rect_color":
            type: Image
            remap: "image_rgb"
            options:
                output_resolution: [128, 128]
                nchannels: 3
                
        "/waypoint_feature":
            type: Vector3
            remap: "waypoint"
            options:
                stamped: True

    action:
        "/cmd":
            type: Twist
            options:
                mode: "action"
    dt: 0.1
