---
    observation:
        "/mux/intervention":
            type: Bool
            remap: "intervention"

        "/realsense/color/image_raw":
            type: Image
            remap: "image_rgb"
            options:
                output_resolution: [64, 64]
                nchannels: 3

    action:
        "/cmd":
            type: AckermannDrive
    dt: 0.1
